axiodl/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    url(r'^boards/', include('boards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^martor/', include('martor.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin.site.site_header = 'AxioDL Admin'
admin.site.set_title = 'AxioDL Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    url(r'^$', views.CategoryListView.as_view(), name='board.index'),
    url(r'^(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board.topics'),
    url(r'^(?P<pk>\d+)/new/$', views.new_topic, name='board.new.topic'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='board.topic.posts'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='board.reply.topic'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='board.edit.post'),
]

www/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    url(r'^boards/', include('boards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
]

admin.site.site_header = 'AxioDL Admin'
admin.site.set_title = 'AxioDL Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models
from django.conf import settings
from django.utils.text import Truncator
from django.core.exceptions import ValidationError
from martor.models import MartorField
import math


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    @property
    def get_children(self):
        return Board.objects.all().filter(category=self)


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, parent_link=True,
                               related_name='+')

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE, parent_link=True)
    locked = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

    def save(self, *args, **kwargs):
        if self.parent and self.parent.name == self.name:
            raise ValidationError('You can\'t have yourself as a parent!')
        return super(Board, self).save(*args, **kwargs)

    @property
    def get_children(self):
        return Board.objects.all().filter(parent=self)


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='topics', on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 20
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 6

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)


class Post(models.Model):
    message = MartorField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name='+', on_delete=models.CASCADE)

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

boards/forms.py
from django import forms
from martor.fields import MartorFormField
from .models import Topic, Post, Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name', 'description', 'parent']


class NewTopicForm(forms.ModelForm):
    message = MartorFormField(
        max_length=4000,
        help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count
from django.utils import timezone
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, ListView, CreateView, DeleteView
from .forms import NewTopicForm, PostForm
from .models import Category, Board, Topic, Post


class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'boards/topics.html'
    paginate_by = 20
    board = None

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset


@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            return redirect('board.topic.posts', pk=board.pk, topic_pk=topic.pk)
    else:
        form = NewTopicForm()
    return render(request, 'boards/new_topic.html', {'board': board, 'form': form})


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'boards/topic_posts.html'
    paginate_by = 10
    topic = None

    def get_context_data(self, **kwargs):
        self.topic.views += 1
        self.topic.save()
        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('pk'), pk = self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset


@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()

            topic.last_updated = timezone.now()
            topic.save()

            topic_url = reverse('board.topic.posts', kwargs={'pk': pk, 'topic_pk': topic_pk})
            topic_post_url = '{url}?page={page}#{id}'.format(
                url=topic_url,
                id=post.pk,
                page=topic.get_page_count()
            )

            return redirect(topic_post_url)
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html', {'topic': topic, 'form': form})


class CategoryListView(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'boards/index.html'


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'boards/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('board.topic.posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)

boards/templates/boards/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'board.index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board.topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a>
    </li>
    <li class="breadcrumb-item"><a
            href="{% url 'board.topic.posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
    <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
    <div class="card border-dark">
    <div class="card-header bg-dark text-light"><div class="card-title">Edit Post</div></div>
        <div class="card-body">
            <form method="post" class="mb-4" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">Save changes</button>
                <a href="{% url 'board.topic.posts' post.topic.board.pk post.topic.pk %}"
                   class="btn btn-outline-secondary"
                   role="button">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

boards/templates/boards/index.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
    {% for category in categories %}
        {% with category.get_children as boards %}
            {% with None as board %}
                <div class="card bg-dark border-dark mb-3">
                    <div class="card-header bg-dark text-light">
                        <div class="card-title"><h1 class="text-light font-weight-bold">{{ category.name }}</h1></div>
                    </div>
                    <div class="card-body bg-dark">
                        {% include 'boards/includes/board_list.html' %}
                    </div>
                    <div class="card-footer bg-dark text-light"></div>
                </div>
            {% endwith %}
        {% endwith %}
    {% endfor %}
{% endblock %}

boards/templates/boards/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'board.index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board.topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
    <div class="card bg-dark border-dark">
        <div class="card-header bg-dark text-light">
            <div class="card-title">New Topic</div>
        </div>
        <div class="card-body bg-light border-dark">
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-sm btn-success btn-block btn-outline-light">Create</button>
            </form>
        </div>
    </div>
{% endblock %}

boards/templates/boards/reply_topic.html
{% extends 'base.html' %}

{% load static martortags %}

{% block title %}Post a reply{% endblock %}

{% include 'includes/simplemde.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'board.index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board.topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board.topic.posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a>
    </li>
    <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block content %}
    <div class="card bg-dark border-dark">
        <div class="card-header bg-dark text-light">
            <div class="card-title">New Topic</div>
        </div>
        <div class="card-body bg-light border-dark">
            <form method="post" class="mb-4">
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">Post a reply</button>
            </form>

            {% for post in topic.posts.all %}
                <div class="card mb-2">
                    <div class="card-body p-3">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">{{ post.created_by.username }}</strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                        </div>
                        {{ post.message|safe_markdown }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

boards/templates/boards/topic_posts.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load gravatar %}
{% load martortags %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'board.index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board.topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

    <div class="mb-4 text-lg-right">
        <a href="{% url 'board.reply.topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
    </div>

    {% for post in topic.posts.all %}
        <div id="{{ post.pk }}"
             class="card bg-dark mb-2 {% if forloop.first %} {% if is_paginated == False or page_obj.number == 1 %}mb-4 border-dark{% else %} mb-2 {% endif %}{% endif %}">
            {% if forloop.first %}
                <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
            {% endif %}
            <div class="card-body bg-light border-dark p-3">
                <div class="row">
                    <div class="col-2">
                        <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100">
                        <small>Posts: {{ post.created_by.posts.count }}</small>
                    </div>
                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">{{ post.created_by.username }}</strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                        </div>
                        {{ post.message|safe_markdown }}
                        {% if post.created_by == user %}
                            <div class="mt-3">
                                <a href="{% url 'board.edit.post' post.topic.board.pk post.topic.pk post.pk %}"
                                   class="btn btn-primary btn-sm" role="button">Edit</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include 'includes/pagination.html' %}

{% endblock %}

boards/templates/boards/topics.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'board.index' %}">Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4 text-lg-right">
        <a href="{% url 'board.new.topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>
    {% if board.get_children %}
        <div class="card bg-dark bg-light mb-3">
            <div class="card-header bg-dark text-light">
                <div class="card-title"><h1 class="text-light font-weight-bold">Subforums</h1></div>
            </div>
            <div class="card-body">
                {% with board.get_children as boards %}
                    {% include 'boards/includes/board_list.html' %}
                {% endwith %}
            </div>
        </div>
    {% endif %}
    <div class="card bg-dark mb-3">
        <div class="card-header bg-dark text-light">
            <div class="card-title"><h1 class="text-light font-weight-bold">{{ board.name }}</h1></div>
        </div>
        <div class="card-body">
            <table class="table bg-light table-striped mb-4">
                <thead class="thead-dark">
                <tr>
                    <th>Topic</th>
                    <th>Starter</th>
                    <th>Replies</th>
                    <th>Views</th>
                    <th>Last Update</th>
                </tr>
                </thead>
                <tbody>
                {% for topic in topics %}
                    <tr>
                        <td><a href="{% url 'board.topic.posts' board.pk topic.pk %}">{{ topic.subject }}</a></td>
                        <td>{{ topic.starter.username }}</td>
                        <td>{{ topic.replies }}</td>
                        <td>{{ topic.views }}</td>
                        <td>
                            {% if topic.last_updated %}
                                {{ topic.last_updated|naturaltime }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="footer">
            {% include 'includes/pagination.html' %}
        </div>
    </div>
{% endblock %}