axiodl/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    url(r'^boards/', include('boards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^martor/', include('martor.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin.site.site_header = 'AxioDL Admin'
admin.site.set_title = 'AxioDL Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib.auth.decorators import permission_required
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    url(r'^pages/create/$', views.create_page, name='pages.create.page'),
    url(r'^pages/list/$', views.PageListView.as_view(), name='pages.list'),
    url(r'^pages/(?P<slug>[^/]+)/$', views.PageView.as_view(), name='pages.view.page'),
    url(r'^pages/(?P<slug>[^/]+)/delete/$', views.PageDeleteView.as_view(), name='pages.delete.page'),
    url(r'^pages/(?P<slug>[^/]+)/edit/$',
         permission_required('pages.edit_page')(views.PageUpdateView.as_view()), name='pages.edit.page'),
]

www/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    url(r'^boards/', include('boards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
]

admin.site.site_header = 'AxioDL Admin'
admin.site.set_title = 'AxioDL Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/Link.py
from django.db import models


class Link(models.Model):
    text = models.CharField(max_length=100)
    link = models.URLField()

    def __str__(self):
        return self.text

core/models/Page.py
from django.db import models, transaction
from django.utils.text import slugify
from django.conf import settings
from django.utils.html import mark_safe
from martor.models import MartorField

from axiodl.fields import UniqueBooleanField


class Page(models.Model):
    page_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='page', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, related_name='+', on_delete=models.CASCADE)
    is_mainpage = UniqueBooleanField(verbose_name='Main Page')
    hidden = models.BooleanField(default=False, blank=True)
    description = models.CharField(max_length=200)
    content = MartorField(null=True, blank=True)
    logo = models.ImageField(upload_to='images', null=True, blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.page_name

    @transaction.atomic
    def save(self, *args, **kwargs):
        print('Page!')
        self.slug = slugify(self.page_name)
        super(Page, self).save(*args, **kwargs)

    def image_tag(self):
        return mark_safe('<img src="/media/images/%s" width="150" height="150" />' % self.logo)

    image_tag.short_description = 'Image'

core/forms/PageForm.py
from django import forms
from django.contrib import admin
from martor.fields import MartorFormField
from ..models import Page


class PageForm(forms.ModelForm):
    content = MartorFormField()
    slug = forms.SlugField(disabled=True, required=False)

    class Meta:
        model = Page
        fields = ['page_name', 'description', 'content', 'logo', 'is_mainpage', 'hidden', 'slug']


class PageFormAdmin(admin.ModelAdmin):
    form = PageForm

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View, UpdateView, DeleteView, ListView
from django.utils import timezone
from django.urls import reverse_lazy
from .forms.PageForm import PageForm
from .models import Page
from axiodl import sitesettings


class IndexView(View):

    def get(self, request, *args, **kwargs):

        if not sitesettings.is_site_locked() or (request.user.is_staff or request.user.is_superuser):
            try:
                page = Page.objects.get(is_mainpage=True)
            except ObjectDoesNotExist:
                page = None

            return render(request, 'core/index.html', {'page': page})
        else:
            return render(request, 'core/site_locked.html')


class PageView(View):

    def get(self, request, slug):

        try:
            page = Page.objects.get(slug=slug)
        except ObjectDoesNotExist:
            page = None

        return render(request, 'core/index.html', {'page': page})


class PageDeleteView(DeleteView):
    model = Page
    template_name = 'core/pages/DeletePage.html'
    success_url = reverse_lazy('home')
    slug_field = 'slug'

    def form_valid(self, form):
        page = form.save(commit=False)
        print(page)
        return self.render_to_response({'page': page})


class PageUpdateView(UpdateView):
    model = Page
    fields = ('page_name', 'description', 'content', 'logo', 'is_mainpage')
    template_name = 'core/pages/NewEditPage.html'
    context_object_name = 'page'
    slug_field = 'slug'

    def form_valid(self, form):
        page = form.save(commit=False)
        page.updated_by = self.request.user
        page.updated_at = timezone.now()
        page.save()
        return redirect('pages.view.page', slug=page.slug)


class PageListView(ListView):
    model = Page
    template_name = 'core/pages/ListPages.html'


@permission_required('core.add_page')
def create_page(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return redirect('home')

        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            page = form.save(commit=False)
            page.created_by = request.user
            page.save()

            return redirect('home')
    else:
        form = PageForm()
    return render(request, 'core/pages/NewEditPage.html', {'form': form})

core/templates/core/index.html
{% extends 'base.html' %}
{% load static core_extras martortags i18n %}

{% block meta %}
    {% if page %}
        {% if page.logo %}
            {% generate_twitter_card 'AxioDL' page.page_name page.description page.logo.url %}
        {% else %}
            {% generate_twitter_card 'AxioDL' page.page_name page.description %}
        {% endif %}
    {% else %}
        {% generate_twitter_card 'AxioDL' 'AxioDL Index' 'Nothing much going on' %}
    {% endif %}
{% endblock %}
{% block breadcrumb-base %}<br/>{% endblock %}
{% block content %}
    {% if page %}
        <div class="card bg-dark border-dark">
            <div class="card-header bg-dark border-dark text-light">
                <div class="row">
                    {% if page.logo %}
                        <div class="col-md-1">
                            <div>
                                <img width="32px" src="{{ page.logo.url }}"/>
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-md-9 text-center">
                        <h2>{{ page.page_name }}</h2>
                    </div>
                </div>
            </div>
            <div class="card-body bg-light border-dark">
                {{ page.content|safe_markdown }}
            </div>
            <div class="card-footer bg-dark">
                <div id="container-fluid">
                    <div class="row">
                        <div class="col-8">
                        <span class="float-left mt-2 text-light">
                            {% blocktrans with name=page.created_by date=page.created_at%}Created on {{ date }} by {{ name }}{% endblocktrans %}
                            {% if page.updated_at %}
                                {% blocktrans with name=page.updated_by date=page.updated_at%}Updated on {{ date }} by {{ name }}{% endblocktrans %}
                            {% endif %}
                        </span>
                        </div>
                        <div class="col-2 text-center">
                            <!-- spacer -->
                        </div>
                        <div class="btn-group">
                            {% if perms.pages.delete_page %}
                                <a href="{% url 'pages.delete.page' page.slug %}"
                                   class="btn btn-danger confirm-delete">{% trans "Delete" %}</a>
                            {% endif %}
                            {% if perms.pages.edit_page %}
                                <a href="{% url 'pages.edit.page' page.slug %}"
                                   class="btn btn-primary">{% trans "Edit" %}</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

core/templates/core/site_locked.html
{% extends 'base.html' %}
{% load i18n site_configuration %}
{% block title %} {%  get_site_name %} - {% get_site_slogan %}{% endblock %}
{% block content %}
<div class="alert-heading">{% trans "Site Locked!" %}</div>
{% endblock %}